version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: retro
      MYSQL_USER: retro
      MYSQL_PASSWORD: retro

  web:
    build:
      context: ./
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      - RAILS_ENV=docker
      - RECAPTCHA_PUBLIC_KEY=abcdefghijklmnopqrst
      - RECAPTCHA_PRIVATE_KEY=abcdefghijklmnopqrst
    links:
      - db:dbserver
    depends_on:
      - db
